name: Release

on:
  push:
    tags:
    - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Setup
      id: setup
      run: |
        echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
        echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: arm-unknown-linux-gnueabihf
        override: true
    
    - name: Install cargo-strip
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: cargo-strip
    
    - name: Install cargo-deb
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: cargo-deb

    - name: Crosscompile binary
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --target=arm-unknown-linux-gnueabihf --release

    - name: Strip binary
      uses: actions-rs/cargo@v1
      with:
        command: strip
        args: --target=arm-unknown-linux-gnueabihf

    - name: Build deb package
      uses: actions-rs/cargo@v1
      with:
        command: deb
        args: --no-build --no-strip --target arm-unknown-linux-gnueabihf     
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.setup.outputs.TAG }}
        release_name: Release ${{ steps.setup.outputs.VERSION }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: target/arm-unknown-linux-gnueabihf/debian/rpi0wcar_${{ steps.setup.outputs.VERSION }}_armhf.deb
        asset_name: rpi0wcar_${{ steps.setup.outputs.VERSION }}_armhf.deb
        asset_content_type: application/vnd.debian.binary-package