name: rpi0wcar

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: rpi0wcar build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: arm-unknown-linux-gnueabihf
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: install
        args: cargo-strip
    - uses: actions-rs/cargo@v1
      with:
        command: install
        args: cargo-deb
    - uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --target=arm-unknown-linux-gnueabihf --release
    - uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: strip
        args: --target=arm-unknown-linux-gnueabihf
    - uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: deb
        args: --no-build --no-strip --target arm-unknown-linux-gnueabihf 
